### ISSUE TITLE
Transition from altool to notarytool

### ISSUE THREAD

**Issue by lufrikas** [The-Nicholas-R-Barrow-Company-LLC/PyMacApp#4]
Hello! I really enjoy using PyMacApp - it's great and saves a lot of time. Unfortunately Apple will no longer support code signing using the "altool" command starting November (tomorrow). Instead, "notarytool" should be used from now on. Any chance that you can update PyMacApp accordingly? That would be awesome. Thanks in advance!

**Comment by ghost** [comment]
@lufrikas thanks for bringing this to my attention! I'll try to push a fix tonight, investigating now.

**Comment by barrownicholas** [comment]
@lufrikas I pushed #v4.0.1 to solve the issue; I made some major changes, some of which are breaking (notably to correct my embarrassing typo in the "Package.notorize" method to the correctly-spelled "Package.notarize". 

Please check out the release notes [here](https://github.com/The-Nicholas-R-Barrow-Company-LLC/PyMacApp/releases/tag/v4.0.1) before upgrading.

I also made a better demo in both the [README.md](https://github.com/The-Nicholas-R-Barrow-Company-LLC/PyMacApp#quickstart-building--packaging-your-app-last-updated-in-v301) and as a stand-alone build.py script [here](https://github.com/The-Nicholas-R-Barrow-Company-LLC/PyMacApp/blob/main/example/build-example.py).

 I already pushed this to PyPi (https://pypi.org/project/PyMacApp/4.0.1/) so you can upgrade when you're ready. 

Test this out and let me know how it goes! Happy to bug-fix as necessary.

**Comment by ghost** [comment]
@lufrikas I'm going to close this issue, but feel free to reopen or open another if this did not solve the problem. Thanks!

**Comment by lufrikas** [comment]
Thanks a lot for the quick fix! Works perfectly now.
